### ISSUE TITLE
Default password and Version of Dude Client to be used?

### ISSUE THREAD

**Issue by zimmerlis** [alexanderfefelov/docker-dude#2]
I have started the docker Image on my Synology NAS and I have exposed the two ports.
Now if I want to connect with the Dude Clinet Version 6.34.6, the message 
"Do you want to update to Version v4.0beta3?" , and the client will not connect!

Password of admin is blank?

**Comment by alexanderfefelov** [comment]
The latest version of Dude Server for Windows is 4.0beta3, so you must use [4.0beta3 client](http://download.mikrotik.com/dude/4.0beta3/dude-install-4.0beta3.exe).

Default credentials are **admin** without password.

**Comment by zimmerlis** [comment]
Thanks, that helps
I have found also this link: http://wiki.mikrotik.com/wiki/Dude_Linux_Installation
that explains why this old Version was used for the Docker Image on Linux.

Thanks, now Dude is running on my NAS (Synology).

**Comment by alexanderfefelov** [comment]
> so you must use 4.0beta3 client.

Link above is now dead. Correct link - <https://github.com/alexanderfefelov/docker-dude/tree/master/installer>. See also #3.
